/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AutoRegister: typeof import('./src/components/AutoRegister.vue')['default']
    GlobalRegister: typeof import('./src/components/GlobalRegister.vue')['default']
    ImportRegister: typeof import('./src/components/ImportRegister.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VlibBackTop: typeof import('@bfehub/vlib-ui/es')['BackTop']
  }
}
